var bookTitle = "";
var pageWidth_1X = 520;
var pageWidth_2X = 992;
var pageHeight_1Y = 738;
var pageHeight_2Y = 1408;
var sliceNumber = 16;
var sliceImgHeight = 88;
var briefLeftPage = 1;
var firstPage = 1;
var lastPage = 368;
var frontIsRight = 0;
var startRight = 0;
var goodsUrl = "";
var IB_listdata = new Array();
var IB_listpage = new Array();
var index = 0;
IB_listdata[index] = "ＩＮＦＯＲＭＡＴＩＯＮ";
IB_listpage[index] = 1;
index++;
IB_listdata[index] = "スタープレート";
IB_listpage[index] = 18;
index++;
IB_listdata[index] = "ワイヤカット放電用プレート";
IB_listpage[index] = 94;
index++;
IB_listdata[index] = "非鉄･アルミ･ステンレスプレート";
IB_listpage[index] = 98;
index++;
IB_listdata[index] = "マシニング加工品";
IB_listpage[index] = 106;
index++;
IB_listdata[index] = "Jブロック";
IB_listpage[index] = 114;
index++;
IB_listdata[index] = "スターダイセット";
IB_listpage[index] = 118;
index++;
IB_listdata[index] = "スターダイセット部品";
IB_listpage[index] = 158;
index++;
IB_listdata[index] = "スター鋳鉄ダイセット";
IB_listpage[index] = 180;
index++;
IB_listdata[index] = "スターＥＤＳシステム";
IB_listpage[index] = 188;
index++;
IB_listdata[index] = "スターポストユニット";
IB_listpage[index] = 194;
index++;
IB_listdata[index] = "スターダイスプリング";
IB_listpage[index] = 212;
index++;
IB_listdata[index] = "精密加工製品";
IB_listpage[index] = 238;
index++;
IB_listdata[index] = "熱処理･表面処理＆ＨＩＰ";
IB_listpage[index] = 244;
index++;
IB_listdata[index] = "品質特性";
IB_listpage[index] = 266;
index++;
IB_listdata[index] = "技術資料";
IB_listpage[index] = 332;
index++;
var soundMode = false;
var isBGM = false;
var soundDir = "sound/";
var usePDF = true;
var isCenterShadow = true;
var isSkinSelection = false;
